routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();



Route::get('/', 'HomeController@index')->name('home');

Route::get('lang/{language}', 'LanguageController@switchLang')->name('lang.switch');

Route::group(['prefix' => 'administrator'], function () {


    Route::get('/login', 'Admin\LoginController@login')->name('admin.login');
    Route::post('/login', 'Admin\LoginController@postLogin')->name('admin.postLogin');

    // Password Reset Routes...

    Route::get('password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('administrator.password.request');
    Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('administrator.password.email');
    Route::get('password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('administrator.password.reset.token');
    Route::post('password/reset', 'Admin\Auth\ResetPasswordController@reset');

});
Route::group(['prefix' => 'administrator', 'middleware' => ['admin']], function () {

    Route::get('/', 'Admin\HomeController@index')->name('home');
    Route::get('/home', 'Admin\HomeController@index')->name('admin.home');


    Route::resource('helpAdmin', 'Admin\HelpAdminController');
    Route::get('helpAdmin/{id}/delete', 'Admin\HelpAdminController@delete')->name('helpAdmin.delete');
    Route::post('helpAdmin/{id}/delete', 'Admin\HelpAdminController@deleteHelpAdmin')->name('helpAdmin.message.delete');
    Route::post('helpAdmin/{id}/suspend', 'Admin\HelpAdminController@suspendHelpAdmin')->name('helpAdmin.message.suspend');
    Route::get('user/{id}/delete', 'Admin\UsersController@delete')->name('user.for.delete');
    Route::post('user/suspend', 'Admin\HelpAdminController@suspend')->name('user.suspend');

    Route::resource('users', 'Admin\UsersController');
    Route::resource('providers_app', 'Admin\ProviderController');
    Route::post('providers_app/suspend', 'Admin\ProviderController@suspend')->name('providers_app.suspend');
    Route::post('accepted','Admin\UsersController@accpetedUser')->name('user.accepted');
    Route::post('refuseUser','Admin\UsersController@refuseUser')->name('user.refuseUser');
    Route::post('reAcceptUser','Admin\UsersController@reAcceptUser')->name('user.reAcceptUser');
    Route::post('suspendUser','Admin\UsersController@suspendUser')->name('user.suspendUser');


    Route::get('settings/aboutus', 'Admin\SettingsController@aboutus')->name('settings.aboutus');
    Route::get('settings/taxs', 'Admin\SettingsController@taxs')->name('settings.taxs');
    Route::get('settings/termsProvider', 'Admin\SettingsController@termsGym')->name('settings.termsGym');
    Route::get('settings/terms', 'Admin\SettingsController@terms')->name('settings.terms');
    Route::get('settings/suspendElement', 'Admin\SettingsController@suspendElement')->name('settings.suspendElement');

//        Route::resource('faqs', 'Admin\FaqsController');

    Route::get('/settings/app-general-settings', 'Admin\SettingsController@appGeneralSettings')->name('settings.app.general');
    Route::get('settings/contacts', 'Admin\SettingsController@contactus')->name('settings.contactus');
    Route::get('settings/minutes_control', 'Admin\SettingsController@minutes_control')->name('settings.minutes_control');


    Route::post('/settings', 'Admin\SettingsController@store')->name('administrator.settings.store');

    Route::post('contactus/reply/{id}', 'Admin\SupportsController@reply')->name('support.reply');
    Route::get('contactus', 'Admin\SupportsController@index')->name('support.index');
    Route::get('contactus/{id}', 'Admin\SupportsController@show')->name('support.show');
    Route::post('support/contact/delete', 'Admin\SupportsController@delete')->name('support.contact.delete');


    Route::resource('supports', 'Admin\SupportsController');
    Route::post('supports/delete', 'Admin\SupportsController@delete')->name('supports.delete');


    Route::post('city/delete/group', 'Admin\CitiesController@groupDelete')->name('cities.group.delete');
    Route::post('cities/delete', 'Admin\CitiesController@delete')->name('city.delete');
    Route::resource('cities', 'Admin\CitiesController');
    Route::post('city/suspend', 'Admin\CitiesController@suspend')->name('city.suspend');

    // -------------------------------------- categories .................
    Route::resource('categories', 'Admin\CategoriesController');
    Route::post('categories/delete', 'Admin\CategoriesController@delete')->name('categories.delete');
    Route::post('categories/suspend', 'Admin\CategoriesController@suspend')->name('categories.suspend');

    // -------------------------------------- places .................
    Route::resource('places', 'Admin\PlacesController');
    Route::post('places/delete', 'Admin\PlacesController@delete')->name('places.delete');
    Route::post('places/suspend', 'Admin\PlacesController@suspend')->name('places.suspend');
    Route::post('places/deleteImage', 'Admin\PlacesController@deleteImage')->name('places.deleteImage');

    // -------------------------------------- ads .................
    Route::resource('ads', 'Admin\AdsController');
    Route::post('ads/delete', 'Admin\AdsController@delete')->name('ads.delete');

    // -------------------------------------- news .................
    Route::resource('newsAdmin', 'Admin\NewsAdminController');
    Route::post('newsAdmin/delete', 'Admin\NewsAdminController@delete')->name('newsAdmin.delete');
    Route::post('newsAdmin/suspend', 'Admin\NewsAdminController@suspend')->name('newsAdmin.suspend');

    Route::resource('reports', 'Admin\ReportsController');

    Route::get('/testImageView', 'Admin\UsersController@testImageView')->name('Provider.testImageView');
    Route::post('/testImage', 'Admin\UsersController@testImage')->name('Provider.testImage');

    Route::resource('reports', 'Admin\ReportsController');

    Route::post('/logout', 'Admin\LoginController@logout')->name('administrator.logout');
});


Route::post('user/update/token', function (Illuminate\Http\Request $request) {

    $user = \App\User::whereId($request->id)->first();


    if ($request->token) {
        $data = \App\Models\Device::where('device', $request->token)->first();
        if ($data) {
            $data->user_id = $user->id;
            $data->save();
        } else {


            $data = new \App\Models\Device;
            $data->device = $request->token;
            $data->user_id = $user->id;
            $data->device_type = 'web';
            $data->save();
        }
    }


})->name('user.update.token');


Route::get('/sub', function (Illuminate\Http\Request $request) {

    $cities =\App\Models\City::whereParentId($request->id)->get();

    if (!empty($cities) && count($cities) > 0){
        return response()->json( $cities);
    }else{

        return response()->json(401);
    }


})->name('getSub');

app/Ad.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ad extends Model
{
    protected $hidden = [
        'created_at','updated_at'
    ];
}

app/Http/Controllers/Admin/AdsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Ad;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AdsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pageName = 'الإعلانات التروجية';
        $ads = Ad::all();
        return view('admin.ads.index',compact('pageName','ads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $pageName = '   إعلان ترويجي';
        return view('admin.ads.create',compact('pageName'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $ads = new Ad();
        $ads->title = $request->title;
        $ads->link  = $request->link;

            if ($request->hasFile('image')):
                $name=  time() . '.' . str_random(20) .$request->image->getClientOriginalName();
                $request->image->move(public_path().'/files/products/', $name);
                $ads->url =  '/public/files/products/' .$name;
            endif;
         $ads->save();

        return response()->json([
            'status' => true,
            "message" => __('trans.addingSuccess',['itemName' => 'الإعلان']),
            "url" => route('ads.index'),

        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ads = Ad::find($id);
        $pageName = '   تعديل الإعلان';

        return view('admin.ads.edit',compact('ads' ,  'pageName'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $ads =  Ad::find($id);
        $ads->title = $request->title;
        $ads->link  = $request->link;

        if ($request->hasFile('image')):
            $name=  time() . '.' . str_random(20) .$request->image->getClientOriginalName();
            $request->image->move(public_path().'/files/products/', $name);
            $ads->url =  '/public/files/products/' .$name;
        endif;
        $ads->save();

        return response()->json([
            'status' => true,
            "message" => __('trans.editSuccess',['itemName' => 'الإعلان']),
            "url" => route('ads.index'),

        ]);
    }

    public function delete(Request $request)
    {
        $model = Ad::findOrFail($request->id);

        if ($model->delete()) {

            return response()->json([
                'status' => true,
                'data' => $model->id
            ]);
        }
    }
}

resources/views/admin/ads/create.blade.php
@extends('admin.layouts.master')
@section('title', __('maincp.users_manager'))


@section('styles')


    <link href="{{ request()->root() }}/public/assets/admin/plugins/select2/dist/css/select2.css" rel="stylesheet" type="text/css">
    <link href="{{ request()->root() }}/public/assets/admin/plugins/select2/dist/css/select2-bootstrap.css" rel="stylesheet" type="text/css">


@endsection
@section('content')



    <form method="POST" action="{{ route('ads.store') }}" enctype="multipart/form-data"
          data-parsley-validate novalidate>
    {{ csrf_field() }}

    <!-- Page-Title -->
        <div class="row">
            <div class="col-lg-12  ">
                <div class="btn-group pull-right m-t-15">
                    <button type="button" class="btn btn-custom  waves-effect waves-light"
                            onclick="window.history.back();return false;"> رجوع <span class="m-l-5"><i
                                    class="fa fa-reply"></i></span>
                    </button>
                </div>
                <h4 class="page-title">إدارة {{$pageName}}</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12  ">
                <div class="card-box">

                    <h4 class="header-title m-t-0 m-b-30"> إضافة {{$pageName}}</h4>

                    <div class="row">

                        <div class="col-xs-12">
                            <div class="form-group">
                                <label for="userName">   عنوان  للإعلان    </label>
                                <input type="text" name="title"
                                       class="form-control requiredFieldWithMaxLenght"
                                       required
                                       placeholder="    عنوان  للإعلان  ..."/>
                                <p class="help-block" id="error_userName"></p>
                                @if($errors->has('name_ar'))
                                    <p class="help-block">
                                        {{ $errors->first('name_ar') }}
                                    </p>
                                @endif
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="form-group">
                                <label for="userName">   لينك  للإعلان    </label>
                                <input type="url" name="link"
                                       class="form-control requiredFieldWithMaxLenght" data-parsley-type="url"
                                       data-parsley-type-message="يجب ادخال   لينك للإعلان صحيح من فضلك "
                                       required
                                       placeholder="    لينك  للإعلان ."/>
                                <p class="help-block" id="error_userName"></p>
                                @if($errors->has('name_ar'))
                                    <p class="help-block">
                                        {{ $errors->first('name_ar') }}
                                    </p>
                                @endif
                            </div>
                        </div>

                        <div class="col-xs-6">

                            <div class="form-group">
                                <label for="usernames">صورة الإعلان  </label>
                                <input type="file" name="image" class="dropify" data-max-file-size="6M"/>
                            </div>

                        </div>


                    </div>


                    <div class="form-group text-right m-t-20">
                        <button class="btn btn-warning waves-effect waves-light m-t-20" type="submit">
                            @lang('maincp.save_data')
                        </button>
                        <button onclick="window.history.back();return false;" type="reset"
                                class="btn btn-default waves-effect waves-light m-l-5 m-t-20">
                            @lang('maincp.disable')
                        </button>
                    </div>

                </div>
            </div><!-- end col -->


        </div>
        <!-- end row -->
    </form>

@endsection



@section('scripts')

    <script src="{{ request()->root() }}/public/assets/admin/plugins/select2/dist/js/select2.min.js" type="text/javascript"></script>


    <script type="text/javascript"
            src="{{ request()->root() }}/public/assets/admin/js/validate-{{ config('app.locale') }}.js"></script>
    <script type="text/javascript">

        function validImages() {

             var images = $( "input[name='image']" ).val();
            if (  images === undefined || images === ""  ) {
                errorMessageTostar(' من فضلك ','من فضلك إختار   صورة   ');
                return false;
            }
            return true;
        }

        $(document).ready(function() {

            $('.js-example-basic-multiple').select2();


        });

        $('form').on('submit', function (e) {

            e.preventDefault();

            var formData = new FormData(this);

            var form = $(this);
            form.parsley().validate();

            if (form.parsley().isValid() && validImages()){

                $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    beforeSend:function () {
                        $('.loading').show();

                    },
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        $('.loading').hide();
                         messageDisplay( 'نجاح' , data.message)
                        setTimeout(function () {
                            window.location.href = data.url;
                        }, 2000);
                    },
                    error: function (data) {
                        $('.loading').hide();
                    }
                });
            }else {
                $('.loading').hide();
            }
        });

       function messageDisplay($title, $message) {
           var shortCutFunction = 'success';
           var msg = $message;
           var title = $title;
           toastr.options = {
               positionClass: 'toast-top-left',
               onclick: null
           };
           var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
           $toastlast = $toast;
       }

       function errorMessageTostar($title, $message) {
           var shortCutFunction = 'error';
           var msg = $message;
           var title = $title;
           toastr.options = {
               positionClass: 'toast-top-left',
               onclick: null
           };
           var $toast = toastr[shortCutFunction](msg, title);
           $toastlast = $toast;
       }

    </script>
@endsection

resources/views/admin/ads/edit.blade.php
@extends('admin.layouts.master')
@section('title', __('maincp.users_manager'))
@section('styles')

    <link href="{{ request()->root() }}/public/assets/admin/plugins/select2/dist/css/select2.css" rel="stylesheet" type="text/css">
    <link href="{{ request()->root() }}/public/assets/admin/plugins/select2/dist/css/select2-bootstrap.css" rel="stylesheet" type="text/css">

@endsection

@section('content')


    <form method="POST" action="{{ route('ads.update', $ads->id) }}" enctype="multipart/form-data"
          data-parsley-validate novalidate>
    {{ csrf_field() }}
    {{ method_field('PUT') }}


    <!-- Page-Title -->
        <div class="row">
            <div class="col-lg-12 ">
                <div class="btn-group pull-right m-t-15">
                    <button type="button" class="btn btn-custom  waves-effect waves-light"
                            onclick="window.history.back();return false;"> رجوع <span class="m-l-5"><i
                                    class="fa fa-reply"></i></span>
                    </button>
                </div>
                <h4 class="page-title">  {{$pageName}}</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12  ">
                <div class="card-box">

                    <h4 class="header-title m-t-0 m-b-30">   {{$pageName}}</h4>

                    <div class="row">

                        <div class="col-xs-12">
                            <div class="form-group">
                                <label for="userName">   عنوان  للإعلان    </label>
                                <input type="text" name="title" value="{{$ads->title}}"
                                       class="form-control requiredFieldWithMaxLenght"
                                       required
                                       placeholder="   باللغة العربية{{$pageName}}  ..."/>
                                <p class="help-block" id="error_userName"></p>
                                @if($errors->has('name_ar'))
                                    <p class="help-block">
                                        {{ $errors->first('name_ar') }}
                                    </p>
                                @endif
                            </div>
                        </div>
                        <div class="col-xs-12">
                            <div class="form-group">
                                <label for="userName">   لينك  للإعلان    </label>
                                <input type="url" name="link" value="{{$ads->link}}"
                                       class="form-control requiredFieldWithMaxLenght" data-parsley-type="url"
                                       data-parsley-type-message="يجب ادخال   لينك للإعلان صحيح من فضلك "
                                       required
                                       placeholder="   باللغة العربية{{$pageName}}  ..."/>
                                <p class="help-block" id="error_userName"></p>
                                @if($errors->has('name_ar'))
                                    <p class="help-block">
                                        {{ $errors->first('name_ar') }}
                                    </p>
                                @endif
                            </div>
                        </div>

                        <div class="col-xs-6">

                            <div class="form-group">
                                <label for="usernames">صورة الإعلان  </label>
                                <input type="hidden" value="{{ $ads->url }}" name="oldImage"/>

                                <input type="file" name="image" class="dropify" data-max-file-size="6M"
                                       data-default-file="{{ request()->root().$ads->url }}"/>
                            </div>

                        </div>


                    </div>


                    <div class="form-group text-right m-t-20">
                        <button class="btn btn-warning waves-effect waves-light m-t-20" type="submit">
                            @lang('maincp.save_data')
                        </button>
                        <button onclick="window.history.back();return false;" type="reset"
                                class="btn btn-default waves-effect waves-light m-l-5 m-t-20">
                            @lang('maincp.disable')
                        </button>
                    </div>

                </div>
            </div><!-- end col -->


        </div>
        <!-- end row -->
    </form>

@endsection



@section('scripts')

    <script src="{{ request()->root() }}/public/assets/admin/plugins/select2/dist/js/select2.min.js" type="text/javascript"></script>


    <script type="text/javascript"
            src="{{ request()->root() }}/public/assets/admin/js/validate-{{ config('app.locale') }}.js"></script>
    <script type="text/javascript">

        function validImages() {

            var oldImages = $( "input[name='oldImage']" ).val();
            var images = $( "input[name='image']" ).val();


            if ( (images === undefined || images === "" ) &&  (oldImages === undefined || oldImages === "" )  ) {
                errorMessageTostar(' من فضلك ','من فضلك إختار   صورة واحدة علي الأقل  ');
                return false;
            }
            return true;
        }

        $(document).ready(function() {

            $(document).on('change', '.category', function () {
                var City_id =   $(this).val();
                var div =   $(this).parent().parent().parent();
                var op =" ";
                var showElement =  div.find('.showElement');
                $.ajax({
                    type:"Get",
                    url: "{{route('getSub')}}",
                    data: {'id': City_id},
                    success:function (data) {

                        if (data.length === undefined){
                            errorMessageTostar('لا يوجد','من فضلك إختار   دولة اخري ');
                        }else {
                            op += '<option  disabled selected>إختر مدينة   </option>';
                            for (var i= 0 ; i <data.length ; i ++){
                                op += '<option value="'+ data[i].id +'">' + data[i].name + '</option>';
                            }
                            div.find('.City_chid').html(" ");
                            div.find('.City_chid').append(op);
                            if (data == null || data == undefined || data.length == 0){
                                showElement.delay(500).slideUp();
                            }else {
                                showElement.delay(500).slideDown();

                            }
                        }

                    },
                    error:function (error) {
                        console.log(error)
                    }
                })
            });

        });


        $('body').on('click', '.removeElement', function () {


            var id = $(this).attr('data-id');
            var url = $(this).attr('data-url');
            swal({
                title: "هل انت متأكد؟",
                type: "error",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "موافق",
                cancelButtonText: "إلغاء",
                confirmButtonClass: 'btn-danger waves-effect waves-light',
                closeOnConfirm: true,
                closeOnCancel: true,
            }, function (isConfirm) {
                if (isConfirm) {
                    $.ajax({
                        type: 'POST',
                        url: url,
                        data: {id: id},
                        dataType: 'json',
                        success: function (data) {

                            if (data.status == true) {
                                var shortCutFunction = 'success';
                                var msg = 'لقد تمت عملية الحذف بنجاح.';
                                var title = data.title;
                                toastr.options = {
                                    positionClass: 'toast-top-left',
                                    onclick: null
                                };
                                var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                                $toastlast = $toast;

//                                $("#image-works" + id)[0].children[2].children[4].click();
                                window.location.reload();

//                                $("#elementRow" + id).remove();
                            }
                            if (data.status == false) {
                                var shortCutFunction = 'warning';
                                var msg =data.message;
                                var title = data.title;
                                toastr.options = {
                                    positionClass: 'toast-top-left',
                                    onclick: null
                                };
                                var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                                $toastlast = $toast;

                            }
                        }
                    });
                }
            });
        });

        $(document).ready(function() {

            $('.js-example-basic-multiple').select2();

            $(function() {
                $("#select_date").on('change', function(){
                    var date = Date.parse($(this).val());

                    if (date < Date.now()   ){
                        errorMessageTostar(' خطأ في التاريخ ','من فضلك إختار تاريخ قدام ');
                        $(this).val('');
                    }
                });
            });

        });

        $('input[name=is_rate]').on('click', function (e) {
            if ($(this).is(':checked')) {
                $('.priceOffer').show();
            } else {
                $('.priceOffer').hide();
            }
        });

        $('input[name=is_comment]').on('click', function (e) {

            if ($(this).is(':checked')) {
                $('.dealField').show();
            } else {
                $('.dealField').hide();
            }
        });





        $('form').on('submit', function (e) {

            e.preventDefault();

            var formData = new FormData(this);

            var form = $(this);
            form.parsley().validate();

            if (form.parsley().isValid() && validImages()){

                $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    beforeSend:function () {
                        $('.loading').show();

                    },
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        $('.loading').hide();
                        messageDisplay( 'نجاح' , data.message)
                        setTimeout(function () {
                            window.location.href = data.url;
                        }, 2000);
                    },
                    error: function (data) {
                        $('.loading').hide();
                    }
                });
            }else {
                $('.loading').hide();
            }
        });

        function messageDisplay($title,$message) {
            var shortCutFunction = 'success';
            var msg = $message;
            var title = $title;
            toastr.options = {
                positionClass: 'toast-top-left',
                onclick: null
            };
            var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
            $toastlast = $toast;
        }

        function errorMessageTostar($title, $message) {
            var shortCutFunction = 'error';
            var msg = $message;
            var title = $title;
            toastr.options = {
                positionClass: 'toast-top-left',
                onclick: null
            };
            var $toast = toastr[shortCutFunction](msg, title);
            $toastlast = $toast;
        }

    </script>
@endsection